### ISSUE TITLE
Could not find a declaration file for module 'react-native-format-currency'. 

### ISSUE THREAD

**Issue by Bamorem** [AwesomeLabs/react-native-format-currency#1]
Could not find a declaration file for module 'react-native-format-currency'. '/.../node_modules/react-native-format-currency/dist/index.js' implicitly has an 'any' type.   Try `npm i --save-dev @types/react-native-format-currency` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-format-currency';`

**Comment by douglasndm** [comment]
Same problem

**Comment by btroia** [comment]
Hi! This issue should be fixed in v0.0.2

**Comment by jacobmolby** [comment]
@btroia Hey it still doesn't work in 0.0.2. It seems that you point the types file to `dist/index.d.ts` while it is actually located in the root (`react-native-format-currency.d.ts`)

**Comment by jacobmolby** [comment]
Another comment. It seems that the types are wrong.
```
// index.ts

type FormatCurrencyFunction = ({
  amount,
  code,
}: {
  amount: number;
  code: string;
}) => [string, number, string];
```

In the declaration file
```
  export function formatCurrency(
    amount: number,
    code: string
  ): [string, number, string];
```
Notice that it takes two arguments and not an object.

**Comment by jacobmolby** [comment]
I've now made a pull request that should fix it 😃

**Comment by btroia** [comment]
> I've now made a pull request that should fix it 😃

Thanks, merged 🎉

**Comment by douglasndm** [comment]
> I've now made a pull request that should fix it 😃

That fixed, thank you
